version: 2

sources:

  - name: ecom # name of the source 
    description: 'details on various transactions concerning: customers, orders, sellers, products & payments '
    schema: public # this is the schema our raw data lives in
    database: vendease_db # this is the name of our database


    tables:
      - name: customers
        description: >
          Contains demographic information about each customer 
        columns: 
          - name: customer_id 
            tests:
              - unique
              - not_null

      - name: order_items
        description: >
          Contains details about each item in an order
        columns:
          - name: order_item_id
            tests:
              - not_null 
          - name: order_id
            tests: 
              - not_null
              - relationships:
                  to: ref('orders')
                  field: order_id

      - name: order_payments
        description: >
          Contains details about payments made for each order
        columns:
          - name: order_id
            tests:
              - not_null

      - name: orders
        description: >
          Contains details about every order made by customers
        columns:
          - name: order_id
            tests:
              - not_null
              - unique
          - name: order_status
            tests:
              - accepted_values:
                  values: ['shipped', 'unavailable', 'invoiced','created', 'approved', 'processing', 'delivered', 'canceled']

      - name: products
        description: >
          Contains details on every product customers can purchase
        columns:
          - name: product_id
            tests:
              - unique
              - not_null

      - name: sellers
        description: >
          Contains details on merchant/seller identities and their locations
        columns:
          - name: seller_id
            tests:
              - not_null
              - unique 